# Generated by Django 4.0.5 on 2022-06-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='location',
        ),
        migrations.AddField(
            model_name='country',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='lon',
            field=models.FloatField(default=0),
        ),
    ]
