# Generated by Django 4.0.5 on 2022-06-13 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gis_app', '0002_remove_country_location_country_lat_country_lon'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('images', models.ImageField(upload_to='')),
                ('lon', models.FloatField(default=0)),
                ('lat', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='country',
            field=models.ForeignKey(null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, to='gis_app.city'),
            preserve_default=b'I01\n',
        ),
    ]
