# Generated by Django 4.0.5 on 2022-07-02 11:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_app', '0004_remove_country_country_city_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.RemoveField(
            model_name='city',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='city',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='country',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='country',
            name='lon',
        ),
        migrations.AddField(
            model_name='city',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='city',
            name='isCapital',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='country',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
    ]
