# Generated by Django 4.0.5 on 2022-07-02 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gis_app', '0005_remove_city_country_remove_city_lat_remove_city_lon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gis_app.country'),
        ),
    ]
