# Generated by Django 4.0.5 on 2022-07-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_app', '0006_city_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='images',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
