# Generated by Django 4.0.5 on 2022-07-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_app', '0007_alter_city_description_alter_city_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='images',
            field=models.ImageField(null=True, upload_to='image'),
        ),
    ]
