# Generated by Django 4.0.5 on 2022-07-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_app', '0008_alter_city_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
